### ISSUE TITLE
16px icon does not get saved

### ISSUE THREAD

**Issue by gingerbeardman** [lemonmojo/IconComposer2x#5]
after saving:
<img width="1792" alt="screen shot 2017-10-24 at 17 02 41" src="https://user-images.githubusercontent.com/49612/31954378-52130a7a-b8dd-11e7-9724-3dda2256a3d6.png">

after loading:
<img width="1701" alt="screen shot 2017-10-24 at 17 02 50" src="https://user-images.githubusercontent.com/49612/31954379-54866342-b8dd-11e7-8c21-0c088350db52.png">

as you can see the 16px icon is missing after the icon is reloaded

**Comment by gingerbeardman** [comment]
I've verified in Preview that the 16x16 image does not exist in the saved icon.

**Comment by lemonmojo** [comment]
Unfortunately that appears to be a bug in iconutil that ships with macOS High Sierra. I've filed a bug report with Apple and copied it to [Open Radar](https://openradar.appspot.com/radar?id=5044378338852864).

**Comment by gingerbeardman** [comment]
Excellent, thanks

**Comment by schroef** [comment]
I still see this issue, yet not on all files. Im still on 10.11.6 and just updated to 1.2 still happens now and then???

**Comment by schroef** [comment]
PS why does this app needs to be fullscreen. It makes dropping in icons to much of a hustle

**Comment by lemonmojo** [comment]
@schroef Interesting. Haven't touched 10.11 in a while. Anyway, since the app just uses `iconutil` under the hood, the issue is likely related to bugs in `iconutil` rather than the app itself. Since it's open source, just try debugging and check where it fails. The app doesn't need to be fullscreen. Not sure why you're stating that?!

**Comment by schroef** [comment]
I'm not sure how you should add icons to this. I do it by dragging in PNG files from a finder window. BUt because the app window is huge and doesnt show all icon sizes. Its a pain in the ass and tedious to add them all. 

<img width="1440" alt="Screen Shot 2019-05-01 at 19 25 30" src="https://user-images.githubusercontent.com/6923008/57049669-11493900-6c47-11e9-81cf-23084f305716.png">

This is my best go at it.
<img width="1407" alt="Screen Shot 2019-05-01 at 19 27 19" src="https://user-images.githubusercontent.com/6923008/57049692-2cb44400-6c47-11e9-880d-417fa6b5796f.png">

What would be nice if you simply select all sizes and the app understand which image should where. That would be hard if it looks at the suffix of an image i guess.
<img width="1407" alt="Screen Shot 2019-05-01 at 19 27 19" src="https://user-images.githubusercontent.com/6923008/57049722-4f465d00-6c47-11e9-8256-efc23b31f542.png">

**Comment by schroef** [comment]
PS perhaps the issue is related that when using iconutils in the terminal you also need to add pixel doubling icons.

That set looks like this
<img width="318" alt="Screen Shot 2019-05-01 at 19 30 00" src="https://user-images.githubusercontent.com/6923008/57049782-8f0d4480-6c47-11e9-80e8-cc54a8afa1fa.png">

But after testing it again. Also iconutils from osx terminal using that method shows no icon in list mode. It does show once i add the icon inside the app. So perhaps its a cache issue?
<img width="238" alt="Screen Shot 2019-05-01 at 19 33 40" src="https://user-images.githubusercontent.com/6923008/57049946-2ecad280-6c48-11e9-802e-52bdb88ce870.png">

I used the codes from this thread; https://stackoverflow.com/questions/12306223/how-to-manually-create-icns-files-using-iconutil
Which got its data from this link; https://developer.apple.com/library/archive/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Optimizing/Optimizing.html

**Comment by lemonmojo** [comment]
@schroef Well, the app was designed on a big screen and I haven't had the need for it to support zooming. Please feel free to submit a PR which improves this.

Also, of course the app generates the `@2x` variants of the icons you drag into it. That's the whole point of the app. Since the original Apple version does not support retina icons. If you take a look at the source code, the app actually uses `iconutil` to do the conversion to .icns.

**Comment by schroef** [comment]
okay thanks! Both have the same issue indeed. At first they wont show the 16px icon. But somehow later it does???

**Comment by gingerbeardman** [comment]
16px icon seems to be saved in Mojave, at least for me
